FROM golang:1.22-alpine

WORKDIR /go/src/github.com/aren55555/grpc-example/garage_server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app

EXPOSE 80
EXPOSE 50051
CMD ["/app"]
