#!/usr/bin/env bash

set -e

mkdir -p parking_client/lib
mkdir -p parking_server/parking

PATH=$PATH:$GOPATH/bin

protoc \
  --proto_path ./protos \
  --grpc_out=./parking_client/lib \
  --plugin=protoc-gen-grpc=`which grpc_ruby_plugin` \
  --ruby_out=./parking_client/lib \
  --go_out=. \
  --go-grpc_out=. \
  ./protos/parking.proto
